version: '3.8'
services:
  postgres_sql:
    image: postgres:latest
    ports:
      - 5432:5432
    container_name: postgres_sql
    restart: always
    environment:
      POSTGRES_PASSWORD: example
      POSTGRES_USER: postgres
      POSTGRES_DB: bizcuit
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./createtable.sql:/docker-entrypoint-initdb.d/createtable.sql
    # volumes:
    #  - ./db:/docker-entrypoint-initdb.d/

  mongodb_server:
    image: mongo
    container_name: mongodb_server
    ports:
      - 27017:27017
      
  backend:
    image: node:latest
    container_name: backend
    restart: always
    depends_on:
      - postgres_sql
    ports:
      - 3500:3500
    volumes:
      - ./backend:/usr/src
      - backend:/usr/src/node_modules
    working_dir: /usr/src
    command: bash -c "npm install && npm run dev"
    env_file:
      - .env

  forntend:
    image: node:latest
    container_name: forntend
    restart: always
    ports:
      - 3000:3000
    volumes:
      - ./forntend:/usr/src
      - forntend:/usr/src/node_modules
    working_dir: /usr/src
    command: bash -c "npm install && npm run dev"
    env_file:
      - .env

volumes:
  backend:
  forntend:
  # db-data: